version: "3.9"
services:
  sageview:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - logData:/sageview/logData
      - logs:/sageview/logs
      - storedData:/sageview/storedData
      - marketData:/sageview/marketData

volumes:
  logs:
    external: False
  logData:
    external: False
  storedData:
    external: False
  marketData:
